"use client";

import { useState } from "react";
import { AppShell } from "@/components/cre-os/AppShell";
import { Panel } from "@/components/cre-os/Panel";
import { Eyebrow } from "@/components/cre-os/Eyebrow";
import { StatusBadge } from "@/components/cre-os/StatusBadge";
import { CommunicationsPanel } from "@/components/cre-os/CommunicationsPanel";
import type { RailSection } from "@/components/cre-os/InsightsRail";
import { WarmthBadge } from "./WarmthBadge";
import { EditContactDialog } from "./EditContactDialog";
import { LogActivityDialog } from "@/components/cre-os/activities/LogActivityDialog";
import type { ContactDetail } from "@/lib/cre-os/relationship-queries";
import type { ThreadSummary } from "@/lib/cre-os/communications-queries";

const fmtMoney = (n: number | null) => {
  if (n === null || !Number.isFinite(n) || n <= 0) return "—";
  if (n >= 1_000_000) return "$" + (n / 1_000_000).toFixed(2) + "M";
  if (n >= 1_000) return "$" + (n / 1_000).toFixed(0) + "K";
  return "$" + n.toLocaleString();
};

/**
 * ContactWorkspace — single-page relationship intelligence view. Header +
 * AI synthesis + communications + linked records + activity timeline +
 * warmth-explainer rail.
 *
 * AI synthesis line is generated by Haiku (with daily caching) and falls
 * back to deterministic synthesis on any error. Same data, same shape.
 */
export function ContactWorkspace({
  contact,
  aiSynthesis,
  threads,
}: {
  contact: ContactDetail;
  aiSynthesis: string;
  threads: ThreadSummary[];
}) {
  const c = contact;
  const [editOpen, setEditOpen] = useState(false);
  const [logActivityOpen, setLogActivityOpen] = useState(false);

  const rail: RailSection[] = [
    {
      eyebrow: "Why this warmth",
      children: (
        <div className="space-y-2 text-[11px] font-body text-cream-dim">
          <div className="flex items-baseline justify-between mb-1">
            <span className="text-cream-subtle">Score</span>
            <span className="font-mono text-cream font-semibold">{c.warmthScore}/100</span>
          </div>
          {c.warmthReasons.length === 0 ? (
            <p className="text-cream-subtle italic">No signals yet.</p>
          ) : (
            <ul className="space-y-1.5">
              {c.warmthReasons.map((r, i) => (
                <li key={i} className="flex items-start gap-2 leading-snug">
                  <span className="mt-1 w-1 h-1 rounded-full bg-cream-subtle shrink-0" />
                  <span>{r}</span>
                </li>
              ))}
            </ul>
          )}
          {c.manualWarmth && (
            <div className="mt-3 pt-2 border-t border-white/[0.04] font-mono text-[10px] text-cream-subtle">
              Override: warmth manually set to <span className="text-cream">{c.manualWarmth}</span>
            </div>
          )}
        </div>
      ),
    },
    {
      eyebrow: "Network at a glance",
      children: (
        <div className="space-y-2 text-[11px] font-body text-cream-dim">
          <RailStat label="Open deals" value={c.linkedDeals.filter((d) => !d.isClosed && !d.isDead).length.toString()} />
          <RailStat label="Closed deals" value={c.linkedDeals.filter((d) => d.isClosed).length.toString()} />
          <RailStat label="Inbound leads" value={c.linkedLeads.length.toString()} />
          <RailStat label="Linked properties" value={c.linkedProperties.length.toString()} />
          <RailStat label="Activity (90d)" value={c.activityCount90d.toString()} />
          <RailStat label="Last touched" value={c.daysSinceTouch !== null ? `${c.daysSinceTouch}d ago` : "Never"} />
        </div>
      ),
    },
    {
      eyebrow: "Quick actions",
      children: (
        <div className="space-y-1.5">
          {c.email && (
            <a href={`mailto:${c.email}`} className="block px-3 py-2 rounded border border-coral-400/30 bg-coral-400/[0.05] hover:bg-coral-400/[0.10] font-body text-[11px] text-cream font-medium transition-colors">
              Email {c.fullName.split(" ")[0]}
            </a>
          )}
          <div className="block px-3 py-2 rounded border border-white/[0.04] bg-white/[0.01] font-body text-[11px] text-cream-subtle">
            Log a call <span className="ml-2 font-mono text-[9px] uppercase">soon</span>
          </div>
          <div className="block px-3 py-2 rounded border border-white/[0.04] bg-white/[0.01] font-body text-[11px] text-cream-subtle">
            Set follow-up <span className="ml-2 font-mono text-[9px] uppercase">soon</span>
          </div>
        </div>
      ),
    },
  ];

  return (
    <AppShell rail={rail}>
      <div className="bg-steward-base/80 backdrop-blur-md border-b border-white/[0.04] -mx-4 px-4 -mt-5 pt-5 pb-5 mb-6 lg:-mx-8 lg:px-8 lg:-mt-6 lg:pt-6">
        <Eyebrow tone="coral">
          {(c.contactType || "Contact").toUpperCase()}
          {c.role && <span className="ml-2 text-cream-subtle">·  {c.role.toUpperCase()}</span>}
        </Eyebrow>
        <div className="mt-2 flex items-start justify-between gap-6 flex-wrap">
          <div className="flex-1 min-w-0">
            <h1 className="font-display font-medium text-3xl text-cream tracking-tight leading-tight">{c.fullName}</h1>
            <div className="mt-1 font-mono text-[11px] text-cream-dim uppercase tracking-wide">
              {[c.email, c.phone, c.companyName, [c.city, c.state].filter(Boolean).join(", ")].filter(Boolean).join(" · ")}
            </div>
            <div className="mt-3 flex items-center gap-2 flex-wrap">
              <WarmthBadge warmth={c.warmth} score={c.warmthScore} manual={!!c.manualWarmth} />
              {c.followUpOverdue && c.nextFollowUp && (
                <StatusBadge size="xs" tone="coral">Follow-up overdue · {c.nextFollowUp}</StatusBadge>
              )}
              {c.daysSinceTouch !== null && (
                <span className="font-mono text-[10px] text-cream-subtle uppercase tracking-eyebrow">
                  · Last touched {c.daysSinceTouch}d ago
                </span>
              )}
            </div>
          </div>
          {/* Action cluster — same pattern as the property workspace.
              Log activity is the primary daily action; Edit details is the
              periodic-update action. */}
          <div className="shrink-0 flex items-center gap-2 flex-wrap">
            <button
              onClick={() => setLogActivityOpen(true)}
              className="px-3 py-2 rounded border border-coral-400/40 bg-coral-400/[0.10] text-coral-300 hover:bg-coral-400/[0.20] font-heading text-[11px] font-semibold uppercase tracking-eyebrow transition-colors"
              title="Log a call, meeting, tour, or note against this contact. Calls/meetings/tours also bump their last-conversation date."
            >
              + Log activity
            </button>
            <button
              onClick={() => setEditOpen(true)}
              className="px-3 py-2 rounded border border-white/10 bg-white/[0.03] text-cream hover:bg-white/[0.06] font-heading text-[11px] font-semibold uppercase tracking-eyebrow transition-colors"
              title="Edit name, email, phone, company, type, warmth, follow-up dates, and notes."
            >
              Edit details
            </button>
          </div>
        </div>
      </div>
      <EditContactDialog
        open={editOpen}
        contactId={c.id}
        initialFullName={c.fullName}
        onClose={() => setEditOpen(false)}
      />
      <LogActivityDialog
        open={logActivityOpen}
        onClose={() => setLogActivityOpen(false)}
        contactId={c.id}
        contextLabel={c.fullName}
      />

      {/* AI synthesis */}
      <div className="relative overflow-hidden rounded-md border border-coral-400/25 bg-gradient-to-r from-steward-surfaceHi/70 via-steward-mid/50 to-steward-surface/30 backdrop-blur-md mb-6">
        <div className="absolute inset-y-0 left-0 w-[3px] bg-coral-400" />
        <div className="px-5 py-4">
          <Eyebrow tone="coral">Relationship summary</Eyebrow>
          <p className="mt-2 font-heading text-[15px] text-cream leading-snug">{aiSynthesis}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          {/* Communications — the new addition */}
          <CommunicationsPanel
            threads={threads}
            num={1}
            emptyMessage={c.email
              ? `No conversations logged yet. Once the inbox watcher (Phase 5) is live, every email between you and ${c.email} will thread here.`
              : "No conversations logged. Email and SMS conversations will appear here once the inbox watcher lands."}
          />

          {/* Linked properties */}
          <Panel eyebrow="Linked properties" num={2} title={`${c.linkedProperties.length} asset${c.linkedProperties.length === 1 ? "" : "s"}`}>
            {c.linkedProperties.length === 0 ? (
              <p className="font-body text-[13px] text-cream-subtle py-4">No properties tied to this contact yet.</p>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {c.linkedProperties.map((p) => (
                  <a key={p.id} href={`/cre-os/properties/${p.slug}`} className="block border border-white/[0.05] rounded p-3 bg-white/[0.02] hover:bg-white/[0.04] transition-colors">
                    <div className="font-heading text-[12px] font-semibold text-cream truncate">{p.name}</div>
                    {(p.city || p.state) && (
                      <div className="font-mono text-[10px] text-cream-subtle truncate mt-0.5">
                        {[p.city, p.state].filter(Boolean).join(", ")}
                      </div>
                    )}
                  </a>
                ))}
              </div>
            )}
          </Panel>

          {/* Linked deals + leads */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Panel eyebrow="Linked deals" num={3} title={`${c.linkedDeals.filter((d) => !d.isClosed && !d.isDead).length} open`}>
              {c.linkedDeals.length === 0 ? (
                <p className="font-body text-[12px] text-cream-subtle py-4">No deals.</p>
              ) : (
                <div className="space-y-2">
                  {c.linkedDeals.map((d) => (
                    <a key={d.id} href={`/cre-os/pipeline/${d.id}`} className="block border border-white/[0.05] rounded p-3 hover:bg-white/[0.04] transition-colors">
                      <div className="flex items-baseline justify-between gap-2">
                        <span className="font-heading text-[12px] font-semibold text-cream truncate">{d.dealName ?? "(unnamed)"}</span>
                        {d.stage && <StatusBadge size="xs" tone={d.isClosed ? "teal" : d.isDead ? "neutral" : "coral"}>{d.stage}</StatusBadge>}
                      </div>
                      <div className="mt-1 font-mono text-[10px] text-cream-subtle">
                        {d.dealType?.replace("_", " ") ?? "—"}{d.price ? ` · ${fmtMoney(d.price)}` : ""}
                      </div>
                    </a>
                  ))}
                </div>
              )}
            </Panel>

            <Panel eyebrow="Inbound leads" num={4} title={`${c.linkedLeads.length} total`}>
              {c.linkedLeads.length === 0 ? (
                <p className="font-body text-[12px] text-cream-subtle py-4">No leads originated by this contact.</p>
              ) : (
                <div className="space-y-2">
                  {c.linkedLeads.slice(0, 8).map((l) => (
                    <a key={l.id} href={`/cre-os/inbox/${l.id}`} className="block border border-white/[0.05] rounded p-3 hover:bg-white/[0.04] transition-colors">
                      <div className="flex items-baseline justify-between gap-2">
                        <span className="font-heading text-[12px] font-semibold text-cream truncate">
                          {l.propertyLabel ?? "(no property)"}
                        </span>
                        {l.urgency && (
                          <StatusBadge size="xs" tone={l.urgency === "hot" ? "coral" : l.urgency === "warm" ? "amber" : "neutral"}>
                            {l.urgency}
                          </StatusBadge>
                        )}
                      </div>
                      <div className="mt-1 font-mono text-[10px] text-cream-subtle">
                        {l.intent ?? "—"} · {l.status ?? "—"}
                      </div>
                    </a>
                  ))}
                </div>
              )}
            </Panel>
          </div>

          {c.notes && (
            <Panel eyebrow="Notes" num={5} title="Free-form context">
              <p className="font-body text-[12px] text-cream-dim whitespace-pre-wrap leading-relaxed">{c.notes}</p>
            </Panel>
          )}
        </div>

        <div className="space-y-6">
          {/* Activity timeline */}
          <Panel eyebrow="Activity" num={6} title={`${c.activity.length} entries`}>
            {c.activity.length === 0 ? (
              <p className="font-body text-[12px] text-cream-subtle py-4">No activity logged yet.</p>
            ) : (
              <div className="relative">
                <div className="absolute left-[7px] top-3 bottom-3 w-px bg-white/[0.06]" />
                <div className="space-y-4">
                  {c.activity.slice(0, 12).map((a, i) => (
                    <div key={a.id} className="relative pl-8">
                      <div className={`absolute left-0 top-1 w-[15px] h-[15px] rounded-full border-2 ${i === 0 ? "border-coral-400 bg-coral-400/30" : "border-white/15 bg-steward-base"}`} />
                      <div className="flex items-baseline gap-3 flex-wrap">
                        <span className="font-mono text-[10px] text-cream-subtle uppercase tracking-eyebrow">{a.when}</span>
                        <span className="font-body text-[12px] text-cream-dim">{a.did}</span>
                      </div>
                      {a.subject && <div className="mt-1 font-heading text-[12px] text-cream">{a.subject}</div>}
                      {a.body && <p className="mt-1 font-body text-[11px] text-cream-dim leading-relaxed line-clamp-3">{a.body}</p>}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </Panel>
        </div>
      </div>
    </AppShell>
  );
}

function RailStat({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-baseline justify-between border-b border-white/[0.04] pb-1.5 last:border-b-0 last:pb-0">
      <span className="text-cream-subtle">{label}</span>
      <span className="font-mono text-cream font-semibold">{value}</span>
    </div>
  );
}
