/**
 * Render Steward's markdown brief into a styled HTML email.
 *
 * The brief is produced as markdown so it can live cleanly in:
 *   1. The daily_briefings.content_text column (no HTML noise)
 *   2. The CRM sidebar (rendered to JSX via the same util)
 *   3. The email body (rendered to inline-styled HTML here)
 *
 * Email constraints: Gmail strips <style> blocks and most external CSS,
 * so every visual rule has to live inline on the element. The styling
 * below is the minimum that survives Gmail + Apple Mail + Outlook web:
 * a single dark wrapper, a content card with serif-friendly type, and
 * a foot of disclaimer/credits.
 *
 * Phone numbers in the markdown come through as `[(312) 555-0142](tel:...)`
 * links — those just work in HTML, no special handling needed.
 */

import { marked } from "marked";

interface RenderOptions {
  /** Subject-line worthy title shown above the content. Already in the markdown usually. */
  brand?: string;
  /** Brief date for the footer (rendered as US-style date string). */
  briefDate?: string;
}

const BRAND = "Stewardship CRE OS";
const ACCENT = "#C2410C"; // coral
const INK = "#1A1A1A";
const INK_DIM = "#525252";
const CREAM = "#F0EDE4";
const CREAM_DIM = "#A39B89";
const SURFACE = "#FAFAFA";
const BORDER = "#E5E5E5";

/**
 * Build the email-wrapped HTML for a Steward brief. The markdown body
 * already includes the headline, sections, tables, etc. — this wrapper
 * just frames it.
 */
export function renderBriefHtml(markdown: string, opts: RenderOptions = {}): string {
  // marked v18 renders cleanly with sensible defaults; we don't need
  // custom renderers here. Tables and inline links work out of the box.
  const inner = marked.parse(markdown, {
    gfm: true,
    breaks: false,
    async: false,
  }) as string;

  const brand = opts.brand ?? BRAND;
  const dateStr = opts.briefDate ?? new Date().toISOString().slice(0, 10);

  // The body styling is deliberately conservative — email clients vary
  // wildly on what they accept. Tested against Gmail web, Gmail iOS,
  // Apple Mail iOS, and Outlook.com.
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(brand)}</title>
</head>
<body style="margin:0;padding:0;background:${SURFACE};font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Helvetica Neue',Arial,sans-serif;color:${INK};">
  <div style="max-width:680px;margin:0 auto;padding:24px 16px;">
    <div style="background:#fff;border:1px solid ${BORDER};border-radius:8px;overflow:hidden;">
      <div style="padding:14px 20px;background:${INK};color:${CREAM};">
        <div style="font-size:10px;letter-spacing:0.12em;text-transform:uppercase;color:${CREAM_DIM};">${escapeHtml(brand)}</div>
        <div style="font-size:14px;margin-top:2px;color:${CREAM};">Daily Brief · ${escapeHtml(dateStr)}</div>
      </div>
      <div style="padding:24px 22px;font-size:14.5px;line-height:1.55;color:${INK};">
${inner.trim()}
      </div>
      <div style="padding:14px 22px;background:${SURFACE};border-top:1px solid ${BORDER};font-size:11.5px;color:${INK_DIM};">
        Generated by Steward, your COO agent. Edit her playbook at
        <code style="background:#fff;border:1px solid ${BORDER};border-radius:3px;padding:1px 4px;color:${ACCENT};">agents/steward.md</code>.
      </div>
    </div>
    <div style="text-align:center;padding:16px 0 0;font-size:11px;color:${INK_DIM};">
      Stewardship CRE OS · single-tenant build · ${escapeHtml(dateStr)}
    </div>
  </div>
</body></html>`;
}

/** Plaintext version of the brief — markdown is already valid plain text. */
export function renderBriefPlaintext(markdown: string): string {
  return markdown;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
